config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  apipie
  ActiveAdmin.routes(self)

  root to: 'home#index'
  devise_for :users, controllers: { confirmations: "confirmations", omniauth_callbacks: 'omniauth_callbacks' }

  resources :users do
    post 'upload_photo', on: :collection
  end

  resources :shows do
    get 'payment', on: :member
  end
  resources :pictures do
    post 'destroy', on: :member, as: 'destroy'
  end

  namespace :api do
    namespace :v1 do
      resources :users, :defaults => { :format => 'json' } do
        get 'search', on: :collection
        post 'pictures', on: :collection
        get 'list/pictures', to: 'users#list_pictures', on: :collection
        delete 'picture', to: 'users#destroy_pictures', on: :collection
        get 'artist', on: :collection
        post 'profile_picture', to: 'users#profile_picture', on: :collection
        delete 'disconnect-stripe', to: 'users#disconnect_stripe', on: :collection
      end
      resources :shows, :defaults => { :format => 'json' } do
        post 'toggle_active', on: :member
        get 'arts', on: :collection
        get 'search', on: :collection
      end
      resources :pictures, :defaults => { :format => 'json' }
      resources :bookings, :defaults => { :format => 'json' } do
        post 'change_status', on: :member
        post 'apply_coupon'
      end
      resources :arts, :defaults => { :format => 'json' }
      resources :showcases
      resources :user_availabilities, path: :availabilities, only: [:index, :show, :create, :destroy]
      resources :credit_cards, only: [:create] do
        patch 'make_default', on: :member
      end
    end
  end

  get '/dashboard', to: 'dashboard#index'
  get '/dashboard/profile', to: 'dashboard#profile', as: 'profile_dashboard'
  get '/dashboard/messages', to: 'dashboard#messages', as: 'messages_dashboard'
  get '/dashboard/shows', to: 'dashboard#shows', as: 'shows_dashboard'
  get '/dashboard/performances', to: 'dashboard#performances', as: 'performances_dashboard'
  get '/dashboard/account', to: 'dashboard#account', as: 'account_dashboard'
  patch '/dashboard/update', to: 'dashboard#update', as: 'update_dashboard'
  get '/dashboard/bookings', to: 'dashboard#bookings', as: 'bookings_dashboard'
  post '/contact', to: 'home#contact', as: 'home_contact'
  post '/society', to: 'home#society', as: 'home_society'
  # route for downloading terms file actions
  get '/download_terms_file/:pdf_for', to: 'home#download_terms_file', as: 'download_terms_file', :defaults => { :format => 'pdf' }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def index

  end

  def profile

  end

  def messages

  end

  def shows

  end

  def performances

  end

  def account

  end

  def update
    @user = current_user
    @user.update_attributes user_params
    render 'profile'
  end

  def bookings

  end

  private

  def user_params
    params.require(:user).permit(:gender, :firstname, :surname, :dob, :phone_number, :bio, :activity, addresses_attributes: [:id, :country, :state, :postcode, :city, :street], language_ids: [])
  end

  def set_user
    @user = current_user
  end

end

app/views/dashboard/_booking.html.slim
.booking
  .row
    .col-md-2
      .photo
        = image_tag booking.user.picture.image.url(:thumb)
      .contact
        = link_to "Contactez #{booking.user.full_name}", "#"
    .col-md-10
      p.name
        span.text-danger = booking.user.full_name
        '
        | par
        '
        span.text-danger = booking.show.title
      p.date
        i.glyphicon.glyphicon-calendar
        '
        = l booking.date.to_date, format: :long
      p.spectators
        i.glyphicon.glyphicon-ok-circle
        '
        = booking.spectators

      - if active
        button.btn.btn-default= "See the details"
hr

app/views/dashboard/_profile_address.html.slim
.address.hide[data-id=(f.object.id.to_i) class=(f.object.errors.empty? ? "" : "has_errors")]
	= f.hidden_field :country, as: :string
	= f.hidden_field :state
	= f.hidden_field :postcode
	= f.hidden_field :city
	= f.hidden_field :street

app/views/dashboard/_tabs.html.slim
.container
  .row
    ul.nav.nav-tabs
      = active_link_to 'Espace personnel', dashboard_path, wrap_tag: :li, active: /^\/dashboard$/
      = active_link_to 'Profile', profile_dashboard_path, wrap_tag: :li, active: /^\/dashboard\/(profile|update)$/
      = active_link_to 'Messages', messages_dashboard_path, wrap_tag: :li
      - if user.shows.size > 0
        = active_link_to 'My Shows', shows_dashboard_path, wrap_tag: :li
        = active_link_to 'My Performances', performances_dashboard_path, wrap_tag: :li
      = active_link_to 'My Bookings', bookings_dashboard_path, wrap_tag: :li
      / = active_link_to 'Account', account_dashboard_path, wrap_tag: :li

app/views/dashboard/account.html.slim
= render "tabs"

br
.container
  br
  .row
    .col-md-3
      br
      ul.nav.nav-pills.nav-stacked
        li.active
          a[href="#payment" data-toggle="tab"]= "Payment Preferences"
        li
          a[href="#information" data-toggle="tab"]= "Payment Information"
        li
          a[href="#security" data-toggle="tab"]= "Security"

    .col-md-9
      .tab-content
        #payment.tab-pane.active

        #information.tab-pane
          / -# FIXME
          / = simple_form_for PaymentMethod.new, url: '/' do |f|
          /   = f.input :user_id, as: :hidden, value: @user.id
          /   .form-group
          /     label.col-md-3.text-right
          /       = "Payment methods"
          /     .col-md-9
          /       = select_tag :payment_methods, options_for_select(@user.payment_methods.map {|pm| [pm.provider, pm.id]})
          /       / = "Add a new payment method"

        a[name="security"]
        #security.tab-pane
          = simple_form_for @user do |f|
            fieldset
              legend Change Password
              = f.input :password
              br
              = f.input :password_confirmation
              br
              br
            .form-actions.col-md-9.col-md-offset-3
              = f.button :submit, 'Change Password'

          br
          br
          br
          br
          br

          = simple_form_for @user do |f|
            fieldset
              legend Change Email
              = f.input :email
              br
              br
            .form-actions.col-md-9.col-md-offset-3
              = f.button :submit, 'Change Email'

app/views/dashboard/bookings.html.slim
= render "tabs"

br
.container
  br
  .row
    .col-md-3
      br
      ul.nav.nav-pills.nav-stacked
        li.active
          a[href="#current" data-toggle="tab"]= "Active bookings"
        li
          a[href="#history" data-toggle="tab"]= "History"
        li
          a[href="#cancelled" data-toggle="tab"]= "Cancelled bookings"

    .col-md-9
      .tab-content
        #current.tab-pane.active
          - if @user.current_bookings.size == 0
            p
              = "You have no future bookings"
          - else
            - @user.current_bookings.each do |booking|
              = render "booking", booking: booking, active: true

        #history.tab-pane
          - if @user.old_bookings.size == 0
            p
              = "You have no old bookings"
          - else
            - @user.old_bookings.each do |booking|
              = render "booking", booking: booking, active: false

        #cancelled.tab-pane
          - if @user.cancelled_bookings.size == 0
            p
              = "You have no cancelled bookings"
          - else
            - @user.cancelled_bookings.each do |booking|
              = render "booking", booking: booking, active: false

app/views/dashboard/index.html.slim
= render "tabs", user: @user

app/views/dashboard/messages.html.slim
= render "tabs"

br
.container
  .row
    .col-md-12
      p
        = "You have no message for the moment"

app/views/dashboard/performances.html.slim
= render "tabs"

br
.container[ng-controller="PerformancesController" ng-init="init()"]
  br
  .row
    .col-md-3
      br
      ul.nav.nav-pills.nav-stacked
        li.active
          a[href="#current" data-toggle="tab"]= "Current bookings"
        li
          a[href="#history" data-toggle="tab"]= "History"
        li
          a[href="#cancelled" data-toggle="tab"]= "Cancelled bookings"

    .col-md-9
      .tab-content
        #current.tab-pane.active
          p[ng-if="(bookings | filter:filterCurrentBookings).length == 0"]
            | You have no current bookings
          performance[ng-repeat="booking in bookings | filter:filterCurrentBookings" booking="booking"]

        #history.tab-pane
          p[ng-if="(bookings | filter:filterOldBookings).length == 0"]
            | You have no old bookings
          performance[ng-repeat="booking in bookings | filter:filterOldBookings" booking="booking"]

        #cancelled.tab-pane
          p[ng-if="(bookings | filter:filterCancelBookings).length == 0"]
            | You have no cancelled bookings
          performance[ng-repeat="booking in bookings | filter:filterCancelBookings" booking="booking"]

app/views/dashboard/profile.html.slim
= render "tabs"
javascript:
  google.maps.event.addDomListener(window, 'load', initialize);
br
.container
  .row
    .col-md-3
      br
      ul.nav.nav-pills.nav-stacked
        li.active
          a[href="#personal" data-toggle="tab"]= "Profil"
        li
          a[href="#reviews" data-toggle="tab"]= "Commentaires"

    .col-md-9
      .tab-content
        #personal.tab-pane.active
          .row
            .page-header
              h2= "Profil"
            .row
              .col-md-4
                h4= "Photo de profil"
                .photo
                  - if @user.picture
                    = image_tag @user.picture.image.url(:medium)

                .btn-upload
                  .btn.btn-success.pull-right= "Changer"
                  form[action=(upload_photo_users_path) enctype="multipart/form-data" method="post"]
                    input[type="file" name="image"]

              .col-md-8
                = simple_form_for @user, html: { class: 'form-horizontal', id: 'profile-form' }, url: update_dashboard_path do |f|
                  fieldset
                    legend= "Informations personnelles"
                    = f.input :gender, include_blank: false
                    = f.input :firstname, "Prénom"
                    = f.input :surname, "Nom", hint: "Cette information ne sera partagée uniquement avec les utilisateur faisant partie d’une réservation confirmée"
                    = f.input :dob, "Date de naissance", start_year: Date.today.year - 96, end_year: Date.today.year
                    .col-md-9.col-md-offset-3
                      = link_to "Actualisez votre adresse email", account_dashboard_path + "#security"
                    = f.input :email, disabled: true
                    = f.input :phone_number, "Numéro de téléphone", hint: "Le numéro permet aux hôtes et aux performeurs de se contacter. Rassurez-vous, cette information ne sera communiquée qu’une fois votre réservation confirmée!"
                  fieldset.form_addresses
                    legend= "Adresses"
                    .form-group.tel.optional
                      label.tel.optional.col-sm-3.control-label for="user_phone_number"  Sélectionner l'adresse
                      .col-sm-9
                        = select_tag "Adresses", options_from_collection_for_select(@user.addresses.select { |a| a.persisted? }, :id, :full_address)
                    - unless @user.addresses.any? { |a| !a.errors.empty? || a.new_record? }
                      - @user.addresses.build
                    = f.simple_fields_for :addresses do |address_form|
                      = render "Adresse du profil", f: address_form
                    .form-group
                      label class="string optional col-sm-3 control-label" Adresse
                      .col-sm-9
                        input id="google-address" class = "string optional form-control"
                      #google-maps class="col-sm-12"
                  fieldset
                    legend= "A propos"
                    = f.input :activity, "Activité"
                    / = f.input :language_id, "Langage", as: :select, collection: Language.all
                    = f.input :bio, as: :text

                  .form-actions
                    .pull-right
                      = f.button :submit, "Enregistrer mon profil", class: "btn btn-success"
                br
                br
                br

        #reviews.tab-pane
          .row
            .page-header
              h2= "Commentaires"
            ul.nav.nav-tabs
              li.active
                a[href="#received_reviews" data-toggle="tab"]= "Commentaires reçus"
              li
                a[href="#sent_reviews" data-toggle="tab"]= "Commentaires envoyés"

          .row
            .tab-content
              #received_reviews.tab-pane.active
                br
                - @user.reviews.each do |review|
                  .row
                    .review
                      .photo.pull-left.col-md-2
                        = image_tag review.booking.user.picture.image.url(:thumb)
                      .col-md-10
                        .row
                          .col-md-5
                            span.name
                              = review.booking.user.full_name
                            |,
                            '
                            span.date
                              = l review.created_at.to_date, format: :long
                          .col-md-4
                            .rating
                              - rating = review.booking.user.rating.try(:round).to_i
                              - rating.times.each do
                                i.glyphicon.glyphicon-star
                        .row
                          .col-md-12
                            blockquote
                              p
                                = review.review

                      .clearfix
                  hr
              #sent_reviews.tab-pane
                br
                - @user.sent_reviews.each do |review|
                  .row
                    .review
                      .photo.pull-left.col-md-2
                        = image_tag review.booking.show.user.picture.image.url(:thumb)
                      .col-md-10
                        .row
                          .col-md-5
                            span.name
                              = review.booking.show.user.full_name
                            |,
                            '
                            span.date
                              = l review.created_at.to_date, format: :long
                          .col-md-4
                            .rating
                              - rating = review.booking.show.user.rating.round
                              - rating.times.each do
                                i.glyphicon.glyphicon-star
                        .row
                          .col-md-12
                            blockquote
                              p
                                = review.review

                      .clearfix
                  hr

app/views/dashboard/shows.html.slim
= render "tabs"

br
.container[ng-controller="ShowController" ng-init="initShows()"]
  br
  .row
    .col-md-3
      a.btn.btn-success[href=(new_show_path)]= "Add New Show"

    .col-md-9
      / - @user.shows.each do |show|
      .col-sm-6.col-md-4[ng-repeat="show in shows"]
        .thumbnail.show
          img[ng-src="{{ show.coverPictureUrl }}"]
          .caption
            a.label.label-danger[ng-href="#" ng-show="!show.active" ng-click="toggleActive(show, $index)"]
              | Disabled (activate)
            a.label.label-success[ng-href="#" ng-show="show.active" ng-click="toggleActive(show, $index)"]
              | Enabled (deactivate)
            h3
              | {{ show.title }}
            .price
              | {{ show.price | currency:undefined:0 }}
            .actions.pull-right
              a[ng-href="/shows/{{show.id}}/edit" title="Edit"]
                i.glyphicon.glyphicon-pencil
              '
              a[href="" title="Delete" ng-click="removeShow(show)"]
                i.glyphicon.glyphicon-trash
            .clearfix